#pragma once

#include <stdint.h>

#define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_MINIMUM)
#define MICROPY_ENABLE_COMPILER (1)
#define MICROPY_ENABLE_GC (1)
#define MICROPY_ENABLE_EXTERNAL_IMPORT (0)
#define MICROPY_MODULE_FROZEN_MPY (0)
#define MICROPY_MODULE_FROZEN_STR (0)
#define MICROPY_HELPER_REPL (0)
#define MICROPY_REPL_EVENT_DRIVEN (0)
#define MICROPY_STACK_CHECK (1)
#define MICROPY_ALLOC_PATH_MAX (128)
#define MICROPY_ALLOC_PARSE_CHUNK_INIT (16)
#define MICROPY_PY_SYS_MODULES (0)
#define MICROPY_PY_SYS_EXIT (0)
#define MICROPY_PY_SYS_PATH (0)
#define MICROPY_PY_SYS_ARGV (0)
#define MICROPY_PY_BUILTINS_FLOAT (0)
#define MICROPY_PY_BUILTINS_COMPLEX (0)
#define MICROPY_LONGINT_IMPL (MICROPY_LONGINT_IMPL_NONE)
#define MICROPY_ERROR_REPORTING (MICROPY_ERROR_REPORTING_NORMAL)
#define MICROPY_HW_BOARD_NAME "MakOS"
#define MICROPY_HW_MCU_NAME "AArch64 EL0"
#define MICROPY_USE_INTERNAL_PRINTF (1)
#define MP_PLAT_PRINT_STRN(str, len) mp_hal_stdout_tx_strn((str), (len))

typedef long mp_off_t;
typedef long ssize_t;
#define alloca(size) __builtin_alloca(size)

#define MP_STATE_PORT MP_STATE_VM
#define MICROPY_PORT_ROOT_POINTERS
